- name: variables from Play Level
  hosts: web
  vars:
    Course: DevOps
    Trainer: Siva Kumar
    Duration: "110 Hours"
  tasks:  
  ansible.builtin.debug:
      msg: I am learning {{Course}}; Trainer is {{Trainer}}; Duration is {{Duration}}.
