- name: variables from files Level
  hosts: web
  vars:
    variables.yaml
  tasks:
  - name: checking variables from files
    ansible.builtin.debug:
      msg: I am learning {{Course}}; Trainer is {{Trainer}}; Duration is {{Duration}}.