- name: variables from prompt level
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter your username
    private: false
  - name: PASSWORD
    prompt: Please enter your password
    private: true
  tasks:
  - name: primt variables
    ansible.builtin.debug: 
      msg: Username is {{USERNAME}}; Password is {{PASSWORD}}.