- name: Variables from Inventory Level
  hosts: localhost
  tasks:
  - name: print variables
    ansible.builtin.debug: 
      msg: I am learning {{Course}}; Trainer is {{Trainer}}; Duration is {{Duration}}. 
