- name: Variables from Inventory Level
  hosts: localhost
  tasks:
  - name: print variables
    ansible.builtin.debug: 
      msg: "Hello {{PERSON}}, Good {{WISHES}}"



#  ansible-playbook -i inventory -e ansible_user=centos -e ansible_password=DevOps321 -e "PERSON=GOKUL" -e "WISHES=WISHES" 09-variables_From_Arguments.yaml     