- name: DataTypes
  hosts: localhost
  vars:
    Name: Siva Kumar   # Key-value pair
    Skills:            # Skills is list type
    - DevOps          
    - Ansible
    - Terrraform
    - Git
    Experience:        # Experience is Map type
      AWS: 10
      Docker: 6
      Kubernetes: 5
    Trainer: true      # Boolean
  tasks:
  - name: Print Key-Value Pair
    ansible.builtin.debug:
      msg: "Name: {{Name}}"
  - name: List
    ansible.builtin.debug:
      msg: "Skills: {{Skills}}"
  - name: List
    ansible.builtin.map:
      msg: "Skills: {{Experience}}"
  - name: Boolean
    ansible.builtin.map:
      msg: "Is he trainer: {{Trainer}}"    

       




