- name: item
  hosts: localhost
  become: true
  tasks:
  - name: loops
    ansible.builtin.debug:
      msg: "Hello {{item}}" # In Ansible, item is a special variable used when looping over a list.
    loop:
    - Rahul
    - Ramesh
    - Suresh  